# Generated by Django 5.0.2 on 2024-05-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('modepass_chiffre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaye',
            fields=[
                ('code_wilaye', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_wilaye_Ar', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_wilaye_fr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
    ]
