# Generated by Django 4.2.7 on 2024-09-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField()),
                ('modepass_chiffre', models.CharField(max_length=128)),
                ('credie', models.IntegerField()),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('photo_de_profile', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaye',
            fields=[
                ('code_wilaye', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_wilaye_Ar', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_wilaye_fr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nombre_joueur', models.IntegerField()),
                ('lieu_fr', models.CharField(max_length=255)),
                ('lieu_ar', models.CharField(max_length=255)),
                ('photo1', models.ImageField(blank=True, upload_to='images')),
                ('photo2', models.ImageField(blank=True, upload_to='images')),
                ('photo3', models.ImageField(blank=True, upload_to='images')),
                ('prix_par_heure', models.IntegerField()),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('ballon_disponible', models.BooleanField(default=False)),
                ('maillot_disponible', models.BooleanField(default=False)),
                ('eclairage_disponible', models.BooleanField(default=False)),
                ('siffler', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('eau', models.BooleanField(default=False)),
                ('gazon_artificiel', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('moughataa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa')),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.joueurs')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains')),
            ],
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye'),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='moughataa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa'),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='wilaye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye'),
        ),
        migrations.CreateModel(
            name='Indisponibilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_indisponibilite', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_done', to='reservations.joueurs')),
                ('evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='reservations.joueurs')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.joueurs')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains')),
            ],
        ),
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('location_ar', models.CharField(max_length=255)),
                ('location_fr', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('moughataa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa')),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
    ]
