# Generated by Django 5.0.2 on 2024-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_telephone',
            field=models.IntegerField(max_length=15),
        ),
    ]
