# Generated by Django 5.0.2 on 2024-05-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_client_numero_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nombre_joueur', models.IntegerField()),
                ('lieu', models.CharField(max_length=255)),
                ('photo1', models.ImageField(blank=True, upload_to='Matchiapp/static/assets/img')),
                ('photo2', models.ImageField(blank=True, upload_to='Matchiapp/static/assets/img')),
                ('photo3', models.ImageField(blank=True, upload_to='Matchiapp/static/assets/img')),
                ('prix_par_heure', models.IntegerField()),
                ('Moughataa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa')),
                ('Wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Cite',
        ),
    ]
