# Generated by Django 5.0.2 on 2024-05-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_moughataa_site_delete_cite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='cite',
        ),
    ]
