# Generated by Django 5.0.2 on 2024-05-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_cite_photo1_alter_cite_photo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut_demande', models.CharField(default='en attente', max_length=25)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('cite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.cite')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('DemandeReservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.demandereservation')),
            ],
        ),
    ]
