# Generated by Django 5.0.2 on 2024-05-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_client_numero_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='matchi_ap/reservation_cite/static/images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='matchi_ap/reservation_cite/static/images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='matchi_ap/reservation_cite/static/images/%y/%m/%d'),
        ),
    ]
