# Generated by Django 5.0.2 on 2024-05-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_alter_cite_photo2_alter_cite_photo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='Moughataa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa'),
        ),
    ]
