# Generated by Django 5.0.2 on 2024-05-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_alter_cite_moughataa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cite',
            old_name='Wilaye',
            new_name='wilaye',
        ),
        migrations.RenameField(
            model_name='demandereservation',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='demandereservation',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='DemandeReservation',
            new_name='demande_reservation',
        ),
        migrations.RemoveField(
            model_name='cite',
            name='Moughataa',
        ),
        migrations.AddField(
            model_name='cite',
            name='ballon_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cite',
            name='eclairage_disponible',
            field=models.BooleanField(default=False, verbose_name='الإنارة'),
        ),
        migrations.AddField(
            model_name='cite',
            name='maillot_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cite',
            name='sonorisation_disponible',
            field=models.BooleanField(default=False, verbose_name='الصوتيات'),
        ),
        migrations.AddField(
            model_name='cite',
            name='moughataa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa'),
        ),
    ]
