# Generated by Django 5.0.2 on 2024-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_rename_wilaye_cite_wilaye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cite',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
