# Generated by Django 4.2.7 on 2024-06-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_alter_cite_latitude_alter_cite_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indisponibilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_indisponibilite', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.joueurs')),
            ],
        ),
        migrations.CreateModel(
            name='Terrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nombre_joueur', models.IntegerField()),
                ('lieu', models.CharField(max_length=255)),
                ('photo1', models.ImageField(blank=True, upload_to='images')),
                ('photo2', models.ImageField(blank=True, upload_to='images')),
                ('photo3', models.ImageField(blank=True, upload_to='images')),
                ('prix_par_heure', models.IntegerField()),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('ballon_disponible', models.BooleanField(default=False)),
                ('maillot_disponible', models.BooleanField(default=False)),
                ('eclairage_disponible', models.BooleanField(default=False, verbose_name='الإنارة')),
                ('sonorisation_disponible', models.BooleanField(default=False, verbose_name='الصوتيات')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('moughataa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa')),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
        migrations.RemoveField(
            model_name='demandereservation',
            name='cite',
        ),
        migrations.RemoveField(
            model_name='demandereservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='demande_reservation',
        ),
        migrations.DeleteModel(
            name='cite',
        ),
        migrations.DeleteModel(
            name='DemandeReservation',
        ),
        migrations.AddField(
            model_name='reservations',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains'),
        ),
        migrations.AddField(
            model_name='indisponibilites',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains'),
        ),
    ]
