# Generated by Django 5.0.6 on 2024-07-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0031_indisponibilites_joueurs_proprietaires_reservations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueurs',
            old_name='email',
            new_name='prenom_joueur',
        ),
        migrations.AddField(
            model_name='joueurs',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='photo_de_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
