# Generated by Django 4.2.7 on 2024-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_joueurs_height_joueurs_weight_evaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proprietaires',
        ),
        migrations.RemoveField(
            model_name='terrains',
            name='sonorisation_disponible',
        ),
        migrations.AddField(
            model_name='terrains',
            name='eau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrains',
            name='gazon_artificiel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terrains',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrains',
            name='siffler',
            field=models.BooleanField(default=False),
        ),
    ]
