# Generated by Django 4.2.7 on 2024-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0034_delete_proprietaires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrains',
            old_name='lieu',
            new_name='lieu_ar',
        ),
        migrations.RenameField(
            model_name='terrains',
            old_name='nom',
            new_name='lieu_fr',
        ),
        migrations.AddField(
            model_name='terrains',
            name='nom_ar',
            field=models.CharField(default='Nom FR par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terrains',
            name='nom_fr',
            field=models.CharField(default='Nom FR par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terrains',
            name='eclairage_disponible',
            field=models.BooleanField(default=False),
        ),
    ]
