# Generated by Django 4.2.7 on 2024-08-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0038_alter_client_id_alter_evaluation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurs',
            name='moughataa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa'),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='wilaye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye'),
        ),
    ]
