# Generated by Django 2.2.22 on 2024-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_auto_20240817_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurs',
            name='visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
