# Generated by Django 2.2.22 on 2024-08-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0041_joueurs_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueurs',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
