# Generated by Django 4.2.7 on 2024-08-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0043_alter_client_id_alter_evaluation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('location_ar', models.CharField(max_length=255)),
                ('location_fr', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('moughataa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.moughataa')),
                ('wilaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wilaye')),
            ],
        ),
    ]
