# Generated by Django 4.2.7 on 2024-09-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0044_academie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.joueurs')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrains')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
