# Generated by Django 4.2.7 on 2024-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0045_demandereservation_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
