# Generated by Django 4.2.7 on 2024-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_client_credie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
