# Generated by Django 5.0.2 on 2024-10-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_client_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('confPwd', models.CharField(max_length=128)),
            ],
        ),
    ]
