# Generated by Django 5.0.2 on 2024-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_client_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrains',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terrains',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
