# Generated by Django 5.0.2 on 2024-10-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0048_alter_terrains_heure_fermeture_and_more'),
        ('reservations', '0048_inscription'),
    ]

    operations = [
    ]
